[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "engressionts"
version = "0.1.0"
description = "A probabilistic time-series forecasting package combining Darts and Engression."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Anusha Tomar" }
]
dependencies = [
    "torch>=2.0.0",
    "darts>=0.29.0",
    "numpy>=1.22.0",
    "pandas>=1.5.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff"
]
